
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PebrIsnani
 */
public class KTP extends javax.swing.JFrame {

    /**
     * Creates new form KTP
     */
    public KTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGJenKel = new javax.swing.ButtonGroup();
        BGkewarga = new javax.swing.ButtonGroup();
        KTP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Lnama = new javax.swing.JLabel();
        Ltanggal_lahir = new javax.swing.JLabel();
        Ljenis_kelamin = new javax.swing.JLabel();
        Lalamat = new javax.swing.JLabel();
        Lrt_rw = new javax.swing.JLabel();
        Lkelurahan = new javax.swing.JLabel();
        Lkecamatan = new javax.swing.JLabel();
        Lkota = new javax.swing.JLabel();
        Lagama = new javax.swing.JLabel();
        Lstatus = new javax.swing.JLabel();
        Lgoldar = new javax.swing.JLabel();
        Lpekerjaan = new javax.swing.JLabel();
        Lkewarga = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        TFtempat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TFtanggal = new javax.swing.JTextField();
        RBlaki_laki = new javax.swing.JRadioButton();
        RBperempuan = new javax.swing.JRadioButton();
        TFalamat = new javax.swing.JTextField();
        TF_RT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_RW = new javax.swing.JTextField();
        TFkelurahan = new javax.swing.JTextField();
        TFkecamatan = new javax.swing.JTextField();
        TFkota = new javax.swing.JTextField();
        Combo_agama = new javax.swing.JComboBox<>();
        Combo_Status = new javax.swing.JComboBox<>();
        Combo_Goldar = new javax.swing.JComboBox<>();
        TFpekerjaan = new javax.swing.JTextField();
        RB_WNA = new javax.swing.JRadioButton();
        RB_WNI = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        Lfoto = new javax.swing.JLabel();
        Bchose = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        Bregister = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KTP.setBackground(new java.awt.Color(204, 0, 204));
        KTP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("FORM ISIAN");

        Lnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lnama.setText("Nama");

        Ltanggal_lahir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Ltanggal_lahir.setText("Tempat/Tanggal lahir");

        Ljenis_kelamin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Ljenis_kelamin.setText("Jenis Kelamin");

        Lalamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lalamat.setText("Alamat");

        Lrt_rw.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lrt_rw.setText("RT/RW");

        Lkelurahan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkelurahan.setText("Kel/Desa");

        Lkecamatan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkecamatan.setText("Kecamatan");

        Lkota.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkota.setText("Kota");

        Lagama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lagama.setText("Agama");

        Lstatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lstatus.setText("Status");

        Lgoldar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lgoldar.setText("Golongan Darah");

        Lpekerjaan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lpekerjaan.setText("Pekerjaan");

        Lkewarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkewarga.setText("Kewarganegaraan");

        jLabel16.setText("/");

        BGJenKel.add(RBlaki_laki);
        RBlaki_laki.setText("Laki-laki");

        BGJenKel.add(RBperempuan);
        RBperempuan.setText("Perempuan");

        jLabel17.setText("/");

        Combo_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Khatolik", "Protestan", "Hindu", "Budha", "KhongHuju" }));

        Combo_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kawin", "Tidak Kawin" }));

        Combo_Goldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        BGkewarga.add(RB_WNA);
        RB_WNA.setText("WNA");

        BGkewarga.add(RB_WNI);
        RB_WNI.setText("WNI");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Pilih Foto (3x4)");

        Lfoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        Bchose.setText("Choose");
        Bchose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BchoseActionPerformed(evt);
            }
        });

        Breset.setBackground(new java.awt.Color(255, 0, 0));
        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });

        Bregister.setBackground(new java.awt.Color(0, 255, 51));
        Bregister.setText("Register");
        Bregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregisterActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 153, 51));
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Masukan Foto Gengs");

        javax.swing.GroupLayout KTPLayout = new javax.swing.GroupLayout(KTP);
        KTP.setLayout(KTPLayout);
        KTPLayout.setHorizontalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KTPLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(KTPLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lnama)
                            .addComponent(Ltanggal_lahir)
                            .addComponent(Lalamat))
                        .addGap(40, 40, 40)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(TFtempat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(RBlaki_laki, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RBperempuan))
                            .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Ljenis_kelamin)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(KTPLayout.createSequentialGroup()
                                    .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lkecamatan)
                                        .addComponent(Lkelurahan)
                                        .addComponent(Lrt_rw)
                                        .addComponent(Lkota))
                                    .addGap(70, 70, 70))
                                .addGroup(KTPLayout.createSequentialGroup()
                                    .addComponent(Lkewarga)
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KTPLayout.createSequentialGroup()
                                    .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Lagama, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lstatus, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lgoldar)
                                    .addComponent(Lpekerjaan))
                                .addGap(64, 64, 64)))
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Combo_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(TF_RT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_RW, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFkelurahan)
                            .addComponent(TFkecamatan)
                            .addComponent(TFkota)
                            .addComponent(TFpekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(RB_WNA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RB_WNI)))))
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(98, 98, 98))
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(Bchose)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(KTPLayout.createSequentialGroup()
                                    .addComponent(Breset)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bregister))
                                .addComponent(Lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );
        KTPLayout.setVerticalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TF_RT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(TF_RW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(KTPLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Lalamat))
                                    .addGroup(KTPLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lnama))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TFtempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ltanggal_lahir)
                                            .addComponent(jLabel16)
                                            .addComponent(TFtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Ljenis_kelamin)
                                            .addComponent(RBlaki_laki)
                                            .addComponent(RBperempuan))
                                        .addGap(27, 27, 27)
                                        .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addComponent(Lrt_rw)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFkelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkelurahan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkecamatan))
                        .addGap(11, 11, 11)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lagama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lstatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lgoldar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lpekerjaan))
                        .addGap(21, 21, 21)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lkewarga)
                            .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RB_WNA)
                                .addComponent(RB_WNI)))
                        .addGap(58, 58, 58))
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bchose)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Breset)
                            .addComponent(Bregister)))))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("FORM KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(KTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregisterActionPerformed
        // TODO add your handling code here:
        OutKTP output = new OutKTP();
        output.TFnama1.setText(TFnama.getText());
        output.TFtempat1.setText(TFtempat.getText());
        output.TFtanggal1.setText(TFtanggal.getText());
        output.TFalamat1.setText(TFalamat.getText());
        output.TFkelurahan1.setText(TFkelurahan.getText());
        output.TF_RT1.setText(TF_RT.getText());
        output.TF_RW1.setText(TF_RW.getText());
        output.TFkecamatan1.setText(TFkecamatan.getText());
        output.TFkota1.setText(TFkota.getText());
        output.TFagama1.setText(this.Combo_agama.getSelectedItem().toString());
        output.TFstatus1.setText(this.Combo_Status.getSelectedItem().toString());
        output.TFgoldar1.setText(this.Combo_Goldar.getSelectedItem().toString());
        output.TFpekerjaan1.setText(TFpekerjaan.getText());
        output.LfotoOut.setIcon(this.Lfoto.getIcon());
        
        String Agama = Combo_agama.getSelectedItem().toString();
        String Status = Combo_Status.getSelectedItem().toString();
        String Goldar = Combo_Goldar.getSelectedItem().toString();
        
        String JenKel = null;
        if(RBlaki_laki.isSelected()){
            output.TFjeniskelamin1.setText(this.RBlaki_laki.getText());
        }else if(RBlaki_laki.isSelected())
            output.TFjeniskelamin1.setText(this.RBperempuan.getText());
        
        String Kewarga = null;
        if(RB_WNA.isSelected()){
            output.TFkewarga1.setText(this.RB_WNA.getText());
        }else if(RB_WNA.isSelected()){
            output.TFjeniskelamin1.setText(this.RB_WNI.getText());
        }
        output.setVisible(true); /*untuk menampilkan atau memunculkan frame output*/
    }//GEN-LAST:event_BregisterActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        // TODO add your handling code here:
        TFnama.setText("");
        TFtempat.setText("");
        TFtanggal.setText("");
        TFalamat.setText("");
        TF_RT.setText("");
        TF_RW.setText("");
        TFkelurahan.setText("");
        TFkecamatan.setText("");
        TFkota.setText("");
        TFpekerjaan.setText("");
        
        BGJenKel.clearSelection();
        BGkewarga.clearSelection();
    }//GEN-LAST:event_BresetActionPerformed

    private void BchoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BchoseActionPerformed
        // TODO add your handling code here:
        JFileChooser OPEN = new JFileChooser();
        int returnVal = OPEN.showOpenDialog(null);
        
        File filegambar = null;
        if(returnVal == JFileChooser.APPROVE_OPTION){
            filegambar = OPEN.getSelectedFile();
            String filename = filegambar.getAbsolutePath();
        }
        try{
            BufferedImage gambar =ImageIO.read(filegambar);
            ImageIcon icon = new ImageIcon(gambar.getScaledInstance(175, 230 , 0));
            Lfoto.setIcon(icon);
           }
        catch(IOException e) {e.getMessage();}
    }//GEN-LAST:event_BchoseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGJenKel;
    private javax.swing.ButtonGroup BGkewarga;
    private javax.swing.JButton Bchose;
    private javax.swing.JButton Bregister;
    private javax.swing.JButton Breset;
    private javax.swing.JComboBox<String> Combo_Goldar;
    private javax.swing.JComboBox<String> Combo_Status;
    private javax.swing.JComboBox<String> Combo_agama;
    private javax.swing.JPanel KTP;
    private javax.swing.JLabel Lagama;
    private javax.swing.JLabel Lalamat;
    private javax.swing.JLabel Lfoto;
    private javax.swing.JLabel Lgoldar;
    private javax.swing.JLabel Ljenis_kelamin;
    private javax.swing.JLabel Lkecamatan;
    private javax.swing.JLabel Lkelurahan;
    private javax.swing.JLabel Lkewarga;
    private javax.swing.JLabel Lkota;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lpekerjaan;
    private javax.swing.JLabel Lrt_rw;
    private javax.swing.JLabel Lstatus;
    private javax.swing.JLabel Ltanggal_lahir;
    private javax.swing.JRadioButton RB_WNA;
    private javax.swing.JRadioButton RB_WNI;
    private javax.swing.JRadioButton RBlaki_laki;
    private javax.swing.JRadioButton RBperempuan;
    private javax.swing.JTextField TF_RT;
    private javax.swing.JTextField TF_RW;
    private javax.swing.JTextField TFalamat;
    private javax.swing.JTextField TFkecamatan;
    private javax.swing.JTextField TFkelurahan;
    private javax.swing.JTextField TFkota;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFpekerjaan;
    private javax.swing.JTextField TFtanggal;
    private javax.swing.JTextField TFtempat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
