/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual_posttest3_136_pebrisudibyo;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author PebrIsnani
 */
public class postest3 extends javax.swing.JFrame {

    /**
     * Creates new form postest3
     */
    public postest3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGJenKel = new javax.swing.ButtonGroup();
        BGkewarga = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelBeranda = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        KTP = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Lnama = new javax.swing.JLabel();
        Ltanggal_lahir = new javax.swing.JLabel();
        Ljenis_kelamin = new javax.swing.JLabel();
        Lalamat = new javax.swing.JLabel();
        Lrt_rw = new javax.swing.JLabel();
        Lkelurahan = new javax.swing.JLabel();
        Lkecamatan = new javax.swing.JLabel();
        Lkota = new javax.swing.JLabel();
        Lagama = new javax.swing.JLabel();
        Lstatus = new javax.swing.JLabel();
        Lgoldar = new javax.swing.JLabel();
        Lpekerjaan = new javax.swing.JLabel();
        Lkewarga = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        TFtempat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TFtanggal = new javax.swing.JTextField();
        RBlaki_laki = new javax.swing.JRadioButton();
        RBperempuan = new javax.swing.JRadioButton();
        TFalamat = new javax.swing.JTextField();
        TF_RT = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TF_RW = new javax.swing.JTextField();
        TFkelurahan = new javax.swing.JTextField();
        TFkecamatan = new javax.swing.JTextField();
        TFkota = new javax.swing.JTextField();
        Combo_agama = new javax.swing.JComboBox<>();
        Combo_Status = new javax.swing.JComboBox<>();
        Combo_Goldar = new javax.swing.JComboBox<>();
        TFpekerjaan = new javax.swing.JTextField();
        RB_WNA = new javax.swing.JRadioButton();
        RB_WNI = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        Lfoto = new javax.swing.JLabel();
        Bchose = new javax.swing.JButton();
        Breset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelCetak = new javax.swing.JPanel();
        OutKTP = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        LfotoOut2 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        TFtempat3 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        TFtanggal3 = new javax.swing.JTextField();
        TFjeniskelamin3 = new javax.swing.JTextField();
        TFgoldar3 = new javax.swing.JTextField();
        TFalamat3 = new javax.swing.JTextField();
        TF_RT3 = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        TF_RW3 = new javax.swing.JTextField();
        TFkelurahan1 = new javax.swing.JTextField();
        TFkecamatan1 = new javax.swing.JTextField();
        TFkota1 = new javax.swing.JTextField();
        TFagama1 = new javax.swing.JTextField();
        TFstatus1 = new javax.swing.JTextField();
        TFpekerjaan1 = new javax.swing.JTextField();
        TFkewarga1 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        TFnama1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("LAYANAN PEMBUATAN KTP");

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new java.awt.CardLayout());

        panelBeranda.setBackground(new java.awt.Color(102, 255, 0));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tgr_1.jpg"))); // NOI18N

        javax.swing.GroupLayout panelBerandaLayout = new javax.swing.GroupLayout(panelBeranda);
        panelBeranda.setLayout(panelBerandaLayout);
        panelBerandaLayout.setHorizontalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelBerandaLayout.setVerticalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelBeranda, "card2");

        panelForm.setBackground(new java.awt.Color(204, 153, 0));

        KTP.setBackground(new java.awt.Color(204, 0, 204));
        KTP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("FORM ISIAN");

        Lnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lnama.setText("Nama");

        Ltanggal_lahir.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Ltanggal_lahir.setText("Tempat/Tanggal lahir");

        Ljenis_kelamin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Ljenis_kelamin.setText("Jenis Kelamin");

        Lalamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lalamat.setText("Alamat");

        Lrt_rw.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lrt_rw.setText("RT/RW");

        Lkelurahan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkelurahan.setText("Kel/Desa");

        Lkecamatan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkecamatan.setText("Kecamatan");

        Lkota.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkota.setText("Kota");

        Lagama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lagama.setText("Agama");

        Lstatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lstatus.setText("Status");

        Lgoldar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lgoldar.setText("Golongan Darah");

        Lpekerjaan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lpekerjaan.setText("Pekerjaan");

        Lkewarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lkewarga.setText("Kewarganegaraan");

        jLabel16.setText("/");

        BGJenKel.add(RBlaki_laki);
        RBlaki_laki.setText("Laki-laki");

        BGJenKel.add(RBperempuan);
        RBperempuan.setText("Perempuan");

        jLabel17.setText("/");

        Combo_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Khatolik", "Protestan", "Hindu", "Budha", "KhongHuju" }));

        Combo_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kawin", "Tidak Kawin" }));

        Combo_Goldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        BGkewarga.add(RB_WNA);
        RB_WNA.setText("WNA");

        BGkewarga.add(RB_WNI);
        RB_WNI.setText("WNI");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Pilih Foto (3x4)");

        Lfoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        Bchose.setText("Choose");
        Bchose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BchoseActionPerformed(evt);
            }
        });

        Breset.setBackground(new java.awt.Color(255, 0, 0));
        Breset.setText("Reset");
        Breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BresetActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 153, 51));
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Masukan Foto Gengs");

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("SILAHKAN KLIK CETAK");

        jLabel9.setBackground(new java.awt.Color(255, 255, 0));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("UNTUK MELIHAT DATA ANDA");

        javax.swing.GroupLayout KTPLayout = new javax.swing.GroupLayout(KTP);
        KTP.setLayout(KTPLayout);
        KTPLayout.setHorizontalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KTPLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(KTPLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lnama)
                            .addComponent(Ltanggal_lahir)
                            .addComponent(Lalamat))
                        .addGap(40, 40, 40)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(TFtempat, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TFtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(RBlaki_laki, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RBperempuan))
                            .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Ljenis_kelamin)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(KTPLayout.createSequentialGroup()
                                    .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lkecamatan)
                                        .addComponent(Lkelurahan)
                                        .addComponent(Lrt_rw)
                                        .addComponent(Lkota))
                                    .addGap(70, 70, 70))
                                .addGroup(KTPLayout.createSequentialGroup()
                                    .addComponent(Lkewarga)
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KTPLayout.createSequentialGroup()
                                    .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Lagama, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lstatus, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lgoldar)
                                    .addComponent(Lpekerjaan))
                                .addGap(64, 64, 64)))
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Combo_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(TF_RT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_RW, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TFkelurahan)
                            .addComponent(TFkecamatan)
                            .addComponent(TFkota)
                            .addComponent(TFpekerjaan, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_agama, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(RB_WNA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RB_WNI)))))
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KTPLayout.createSequentialGroup()
                                    .addComponent(Breset)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)))
                                .addComponent(Lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(Bchose)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(80, 80, 80))))
        );
        KTPLayout.setVerticalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TF_RT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(TF_RW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(KTPLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Lalamat))
                                    .addGroup(KTPLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lnama))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TFtempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ltanggal_lahir)
                                            .addComponent(jLabel16)
                                            .addComponent(TFtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Ljenis_kelamin)
                                            .addComponent(RBlaki_laki)
                                            .addComponent(RBperempuan))
                                        .addGap(27, 27, 27)
                                        .addComponent(TFalamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15)
                                .addComponent(Lrt_rw)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFkelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkelurahan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFkecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkecamatan))
                        .addGap(11, 11, 11)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lkota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lagama))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lstatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Combo_Goldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lgoldar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TFpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lpekerjaan))
                        .addGap(21, 21, 21)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lkewarga)
                            .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RB_WNA)
                                .addComponent(RB_WNI)))
                        .addGap(58, 58, 58))
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Lfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bchose)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                                .addComponent(Breset)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(25, 25, 25))
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addContainerGap())))))
        );

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(panelForm, "card3");

        panelCetak.setBackground(new java.awt.Color(0, 153, 51));

        OutKTP.setBackground(new java.awt.Color(0, 204, 204));
        OutKTP.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel54.setText("KARTU TANDA PENDUDUK (KTP)");

        LfotoOut2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel55.setText("NAMA");

        jLabel56.setText("TEMPAT");

        jLabel57.setText("/");

        jLabel58.setText("TANGGAL LAHIR");

        jLabel59.setText("JENIS KELAMIN");

        jLabel60.setText("GOLONGAN DARAH");

        jLabel61.setText("ALAMAT");

        jLabel62.setText("RT");

        jLabel63.setText("/");

        jLabel64.setText("RW");

        jLabel65.setText("KEL");

        jLabel66.setText("/");

        jLabel67.setText("DESA");

        jLabel68.setText("KECAMATAN");

        jLabel69.setText("KOTA");

        jLabel70.setText("AGAMA");

        jLabel71.setText("STATUS");

        jLabel72.setText("PEKERJAAN");

        jLabel73.setText("KEWARGANEGARAAN");

        TFtempat3.setEditable(false);

        jLabel74.setText("/");

        TFtanggal3.setEditable(false);

        TFjeniskelamin3.setEditable(false);

        TFgoldar3.setEditable(false);

        TFalamat3.setEditable(false);

        TF_RT3.setEditable(false);

        jLabel75.setText("/");

        TF_RW3.setEditable(false);
        TF_RW3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_RW3ActionPerformed(evt);
            }
        });

        TFkelurahan1.setEditable(false);

        TFkecamatan1.setEditable(false);

        TFkota1.setEditable(false);

        TFagama1.setEditable(false);
        TFagama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFagama1ActionPerformed(evt);
            }
        });

        TFstatus1.setEditable(false);

        TFpekerjaan1.setEditable(false);

        TFkewarga1.setEditable(false);

        TFnama1.setEditable(false);

        javax.swing.GroupLayout OutKTPLayout = new javax.swing.GroupLayout(OutKTP);
        OutKTP.setLayout(OutKTPLayout);
        OutKTPLayout.setHorizontalGroup(
            OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutKTPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OutKTPLayout.createSequentialGroup()
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel58))
                    .addComponent(jLabel55)
                    .addComponent(jLabel59)
                    .addComponent(jLabel61)
                    .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel60, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OutKTPLayout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel67))
                            .addGroup(OutKTPLayout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel64))
                            .addComponent(jLabel68)
                            .addComponent(jLabel69)))
                    .addComponent(jLabel70))
                .addGap(23, 23, 23)
                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OutKTPLayout.createSequentialGroup()
                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFjeniskelamin3)
                            .addComponent(TFgoldar3)
                            .addGroup(OutKTPLayout.createSequentialGroup()
                                .addComponent(TF_RT3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_RW3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(TFalamat3)
                            .addComponent(TFkelurahan1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutKTPLayout.createSequentialGroup()
                                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(OutKTPLayout.createSequentialGroup()
                                        .addComponent(TFtempat3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel74)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFtanggal3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                    .addComponent(TFnama1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel76, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(36, 36, 36)
                        .addComponent(LfotoOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(OutKTPLayout.createSequentialGroup()
                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFkecamatan1)
                            .addComponent(TFkota1)
                            .addComponent(TFagama1)
                            .addComponent(TFstatus1)
                            .addComponent(TFpekerjaan1)
                            .addComponent(TFkewarga1))
                        .addGap(249, 249, 249))))
            .addGroup(OutKTPLayout.createSequentialGroup()
                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel54)
                    .addGroup(OutKTPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel71)
                            .addComponent(jLabel72)
                            .addComponent(jLabel73))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OutKTPLayout.setVerticalGroup(
            OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutKTPLayout.createSequentialGroup()
                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OutKTPLayout.createSequentialGroup()
                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(OutKTPLayout.createSequentialGroup()
                                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(OutKTPLayout.createSequentialGroup()
                                        .addComponent(jLabel54)
                                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(OutKTPLayout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(LfotoOut2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(OutKTPLayout.createSequentialGroup()
                                                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(OutKTPLayout.createSequentialGroup()
                                                        .addGap(40, 40, 40)
                                                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel55)
                                                            .addComponent(jLabel76)))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutKTPLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(TFnama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutKTPLayout.createSequentialGroup()
                                                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutKTPLayout.createSequentialGroup()
                                                                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OutKTPLayout.createSequentialGroup()
                                                                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                            .addComponent(jLabel56)
                                                                            .addComponent(jLabel57)
                                                                            .addComponent(jLabel58)
                                                                            .addComponent(TFtempat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addComponent(jLabel74)
                                                                            .addComponent(TFtanggal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabel59))
                                                                    .addComponent(TFjeniskelamin3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel60))
                                                            .addComponent(TFgoldar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel61))
                                                    .addComponent(TFalamat3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel62)
                                                    .addComponent(jLabel63)
                                                    .addComponent(jLabel64)
                                                    .addComponent(TF_RT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel75)
                                                    .addComponent(TF_RW3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(OutKTPLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel65)
                                                            .addComponent(jLabel66)
                                                            .addComponent(jLabel67))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel68))
                                                    .addGroup(OutKTPLayout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(TFkelurahan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(4, 4, 4)
                                                        .addComponent(TFkecamatan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel69)
                                            .addComponent(TFkota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel70))
                                    .addComponent(TFagama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel71))
                            .addComponent(TFstatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel72))
                    .addComponent(TFpekerjaan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OutKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel73)
                    .addComponent(TFkewarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCetakLayout = new javax.swing.GroupLayout(panelCetak);
        panelCetak.setLayout(panelCetakLayout);
        panelCetakLayout.setHorizontalGroup(
            panelCetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCetakLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(OutKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        panelCetakLayout.setVerticalGroup(
            panelCetakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCetakLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(OutKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelCetak, "card4");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 13, 0));

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("BERANDA");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 255, 255));
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("DAFTAR");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setBackground(new java.awt.Color(0, 255, 255));
        jButton3.setForeground(new java.awt.Color(153, 0, 0));
        jButton3.setText("CETAK");
        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);

        jButton4.setBackground(new java.awt.Color(0, 255, 255));
        jButton4.setForeground(new java.awt.Color(153, 0, 0));
        jButton4.setText("EXIT");
        jButton4.setBorder(new javax.swing.border.MatteBorder(null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/download.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DINAS PENDUDUK DAN PENCATATAN SIPIL (DISDUKCAPIL)");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("KABUPATEN KUTAI KARTANEGARA");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PROVINSI KALIMANTAN TIMUR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        panelBeranda.setVisible(true);
        panelForm.setVisible(false);
        panelCetak.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        panelForm.setVisible(true);
        panelBeranda.setVisible(false);
        panelCetak.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        panelCetak.setVisible(true);
        panelBeranda.setVisible(false);
        panelForm.setVisible(false);
        TFnama1.setText(TFnama.getText());
        TFtempat3.setText(TFtempat.getText());
        TFtanggal3.setText(TFtanggal.getText());
        TFalamat3.setText(TFalamat.getText());
        TFkelurahan1.setText(TFkelurahan.getText());
        TF_RT3.setText(TF_RT.getText());
        TF_RW3.setText(TF_RW.getText());
        TFkecamatan1.setText(TFkecamatan.getText());
        TFkota1.setText(TFkota.getText());
        TFagama1.setText(this.Combo_agama.getSelectedItem().toString());
        TFstatus1.setText(this.Combo_Status.getSelectedItem().toString());
        TFgoldar3.setText(this.Combo_Goldar.getSelectedItem().toString());
        TFpekerjaan1.setText(TFpekerjaan.getText());
        LfotoOut2.setIcon(this.Lfoto.getIcon());
        
        
        String Agama = Combo_agama.getSelectedItem().toString();
        String Status = Combo_Status.getSelectedItem().toString();
        String Goldar = Combo_Goldar.getSelectedItem().toString();
        
        String JenKel = null;
        if(RBlaki_laki.isSelected()){
            TFjeniskelamin3.setText(this.RBlaki_laki.getText());
        }else if(RBlaki_laki.isSelected())
            TFjeniskelamin3.setText(this.RBperempuan.getText());
        
        String Kewarga = null;
        if(RB_WNA.isSelected()){
            TFkewarga1.setText(this.RB_WNA.getText());
        }else if(RB_WNI.isSelected()){
            TFkewarga1.setText(this.RB_WNI.getText());
        }
        //output.setVisible(true); /*untuk menampilkan atau memunculkan frame output*/
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BchoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BchoseActionPerformed
        // TODO add your handling code here:
        JFileChooser OPEN = new JFileChooser();
        int returnVal = OPEN.showOpenDialog(null);

        File filegambar = null;
        if(returnVal == JFileChooser.APPROVE_OPTION){
            filegambar = OPEN.getSelectedFile();
            String filename = filegambar.getAbsolutePath();
        }
        try{
            BufferedImage gambar =ImageIO.read(filegambar);
            ImageIcon icon = new ImageIcon(gambar.getScaledInstance(175, 230 , 0));
            Lfoto.setIcon(icon);
        }
        catch(IOException e) {e.getMessage();}
    }//GEN-LAST:event_BchoseActionPerformed

    private void BresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BresetActionPerformed
        // TODO add your handling code here:
        TFnama.setText("");
        TFtempat.setText("");
        TFtanggal.setText("");
        TFalamat.setText("");
        TF_RT.setText("");
        TF_RW.setText("");
        TFkelurahan.setText("");
        TFkecamatan.setText("");
        TFkota.setText("");
        TFpekerjaan.setText("");

        BGJenKel.clearSelection();
        BGkewarga.clearSelection();
    }//GEN-LAST:event_BresetActionPerformed

    private void TF_RW3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_RW3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_RW3ActionPerformed

    private void TFagama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFagama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFagama1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(postest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new postest3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGJenKel;
    private javax.swing.ButtonGroup BGkewarga;
    private javax.swing.JButton Bchose;
    private javax.swing.JButton Breset;
    private javax.swing.JComboBox<String> Combo_Goldar;
    private javax.swing.JComboBox<String> Combo_Status;
    private javax.swing.JComboBox<String> Combo_agama;
    private javax.swing.JPanel KTP;
    private javax.swing.JLabel Lagama;
    private javax.swing.JLabel Lalamat;
    private javax.swing.JLabel Lfoto;
    public static javax.swing.JLabel LfotoOut2;
    private javax.swing.JLabel Lgoldar;
    private javax.swing.JLabel Ljenis_kelamin;
    private javax.swing.JLabel Lkecamatan;
    private javax.swing.JLabel Lkelurahan;
    private javax.swing.JLabel Lkewarga;
    private javax.swing.JLabel Lkota;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lpekerjaan;
    private javax.swing.JLabel Lrt_rw;
    private javax.swing.JLabel Lstatus;
    private javax.swing.JLabel Ltanggal_lahir;
    private javax.swing.JPanel OutKTP;
    private javax.swing.JRadioButton RB_WNA;
    private javax.swing.JRadioButton RB_WNI;
    private javax.swing.JRadioButton RBlaki_laki;
    private javax.swing.JRadioButton RBperempuan;
    private javax.swing.JTextField TF_RT;
    public static javax.swing.JTextField TF_RT3;
    private javax.swing.JTextField TF_RW;
    public static javax.swing.JTextField TF_RW3;
    public static javax.swing.JTextField TFagama1;
    private javax.swing.JTextField TFalamat;
    public static javax.swing.JTextField TFalamat3;
    public static javax.swing.JTextField TFgoldar3;
    public static javax.swing.JTextField TFjeniskelamin3;
    private javax.swing.JTextField TFkecamatan;
    public static javax.swing.JTextField TFkecamatan1;
    private javax.swing.JTextField TFkelurahan;
    public static javax.swing.JTextField TFkelurahan1;
    public static javax.swing.JTextField TFkewarga1;
    private javax.swing.JTextField TFkota;
    public static javax.swing.JTextField TFkota1;
    private javax.swing.JTextField TFnama;
    public static javax.swing.JTextField TFnama1;
    private javax.swing.JTextField TFpekerjaan;
    public static javax.swing.JTextField TFpekerjaan1;
    public static javax.swing.JTextField TFstatus1;
    private javax.swing.JTextField TFtanggal;
    public static javax.swing.JTextField TFtanggal3;
    private javax.swing.JTextField TFtempat;
    public static javax.swing.JTextField TFtempat3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelCetak;
    private javax.swing.JPanel panelForm;
    // End of variables declaration//GEN-END:variables
}
